replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

httpRoute:
  enabled: false

resources: {}
